(function(c){var e=window.AmazonUIPageJS||window.P,m=e._namespace||e.attributeErrors,a=m?m("AmazonRushRouter",""):e;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,e,m){c.when("A").register("rush-routable-application-base",function(a){return a.createClass({init:function(d){this.applicationName=d},name:function(){return this.applicationName},unload:function(d){return{}},load:function(d,a){return!0}})});"use strict";c.when("A").register("rush-router-html5-history-support",
function(a){var d=a.$.extend;return function(a){function n(f,a,d){a=d.match(a);return{major:f&&a&&a[1]?parseInt(a[1],10):-1,minor:f&&a&&a[2]?parseInt(a[2],10):-1}}function c(f){if(!f||!f.url&&!f.state)return!1;h.replaceState(d({},h.state(),f.state),h.title(),f.url);return!0}var h=a||{userAgent:e.navigator.userAgent,pushState:function(f,a,d){e.history.pushState(f,a,d)},replaceState:function(a,d,h){e.history.replaceState(a,d,h)},title:function(){return document.title},state:function(){return e.history.state},
addStateChangeHandler:function(a){e.addEventListener("popstate",a,!1)},removeStateChangeHandler:function(a){e.removeEventListener("popstate",a)},hasNativeHistorySupport:function(){return e.history&&e.history.replaceState}};return{isSupportedBrowser:function(){var a=h.userAgent,d=/iPhone|iPad|iPod/.test(a),e=-1!==a.indexOf("Android"),c=n(d,/OS ([0-9]+)(?:_([0-9]+))?/,a),a=n(e,/Android ([0-9]+)(?:\.([0-9]+))?/,a);return h.hasNativeHistorySupport()&&!(d&&5>c.major)&&!(e&&4>a.major)&&!(e&&4===a.major&&
2>a.minor)},to:function(a){if(!a||!a.url&&!a.state)return!1;h.pushState(d({},a.state||{}),h.title(),a.url);return!0},replace:c,back:function(){h.history.back()},state:function(a){a&&c({state:a});return h.state()||{}},addStateChangeHandler:h.addStateChangeHandler,removeStateChangeHandler:h.removeStateChangeHandler}}});"use strict";c.when("A").register("rush-router-pattern-parser",function(a){function d(w,b){return b?(a.isArray(b)||(b=[b]),b.concat(a.isArray(w)?w:[w])):w}function e(a){return a.replace(t,
"\\$\x26")}function c(a){return decodeURIComponent((a||"").replace(/\+/g," "))}function m(a){var b="",d=[],l=[],g,k;k=0;var c;g=0;c=[];var h,f,n;for(f=0;f<a.length;f++)h=a[f],n=0===f||0<f&&"\\"!==a[f-1],"{"===h&&n?(g++,c.push(h),1===g&&c.push("\x3c")):("}"===h&&n&&(g--,0===g&&c.push("\x3e")),c.push(h));for(a=c.join("");g=z.exec(a);)g.index!==k&&(l.push(a.slice(k,g.index)),b+=e(a.slice(k,g.index))),g[1]?(k={},g[3]?(b+="("+g[3]+")",c=g[3].match(A),k[g[1]]=c?c.length+1:1):(b+="([^/]+)",k[g[1]]=1),d.push(k)):
"**"===g[0]?(b+="(.*)",d.push({wildcard:1})):"*"===g[0]?(b+="(.*?)",d.push({wildcard:1})):"("===g[0]?b+="(?:":")"===g[0]&&(b+=")?"),l.push(g[0]),k=z.lastIndex;k!==a.length&&(l.push(a.slice(k,a.length)),b+=e(a.slice(k,a.length)));"/"!==a.charAt(0)&&(a="/"+a);"/"!==a.charAt(a.length-1)&&(b+="/?");"*"===l[l.length-1]&&(b+="$");b="^"+b;return{pattern:a,regexpSource:b,regex:new RegExp(b,"i"),paramNames:d,tokens:l}}function h(a){a in q||(q[a]=m(a));return q[a]}function f(w,b){var f={},l=!1,g=h(w),k=b.match(g.regex),
e=null,p;if(k){l=!0;p=k[0];(e=b.substr(p.length))&&"/"===p.charAt(p.length-1)&&(e="/"+e);a.map(k.slice(1),function(a){return c(a)});var m=1;for(p=0;p<g.paramNames.length;p++)a.each(g.paramNames[p],function(a,b){for(var g=0;g<a;g++)f[b]=d(k[m],f[b]),m++})}return{isMatch:l,remainingPathname:e,params:f}}function y(a){var b={},f,e,g;if(!a)return b;"?"===a[0]&&(a=a.slice(1));a=a.split("\x26");for(g=0;g<a.length;g++)f=a[g].split("\x3d"),e=c(f.shift()),f=f.length?c(f.join("\x3d")):null,e&&(b[e]=d(f,b[e]));
return b}var z=/\{<([a-zA-Z_][\w-]*)(:(.+?(?=>\})))?>\}|\*\*|\*|\(|\)/g,t=/[.*+?\^${}()|\[\]\\]/g,A=/(?!\\)(\()/g,q={};return{parsePattern:m,matchPathname:f,parseQueryString:y,matchLocation:function(e,b){var c=f(e,b.pathname),h;if(!1===c.isMatch||c.remainingPathname)return c.isMatch=!1,c;h=y(b.search);a.each(h,function(a,b){c.params[b]=d(a,c.params[b])});return c}}});"use strict";c.when("A").register("rush-route",function(a){return a.createClass({init:function(a,c,e){this.application=function(){return a};
this.pattern=function(){return c};this.handler=function(){return e}}})});"use strict";c.when("a-util","rush-router-pattern-parser","rush-route","rush-router-html5-history-support","rush-routable-application-base","rush-router-url-parser").register("R",function(a,d,F,n,C,h){function f(a){return"function"===typeof a}function y(a){var b=document.createElement("a");b.href=a.href;b.setAttribute("href",b.href);return b.protocol+"//"+b.host}function z(){return document.location}function t(a,b){function n(a,
b){var d,c,f;f=(b=b||u)&&b.name();if(b&&(d=k(a,f)))return{route:d.route,params:d.params};for(c in v)if(c!==f&&v.hasOwnProperty(c)&&(d=k(a,c)))return{route:d.route,params:d.params};return!1}function l(a,b,d,c){var f;if(!0===B)return!1;a=a||r();f=n(a,u);if(!1!==f)return!!q(f.route,f.params,a,d,b,c);!1!==b&&t(a.href);return!1}function g(a){l(m,m,a)}function k(a,b){var c=v[b],f=!1,g,e,h;for(h=0;h<c.length;h++)if(g=c[h],e=d.matchLocation(g.pattern(),a),e.isMatch){e.route=g;f=e;break}return f}function q(a,
b,d,c,f,e){c=a.application();return u!==c&&!1===p(d,c)?!1:!1===a.handler().call(d,b,d,e)?(!1!==f&&t(d.href),!1):!0}function p(a,b){var d,c=null!==u&&u!==b;if(c&&(d=u.unload(a),!1===d))return t(a.href),!1;u=b;if(!1===b.load(a,d)){if(c)t(a.href);else throw Error("FATAL: Router: app.load() failed on startup.");return!1}return!0}function t(a){r().href===a?r().reload(!0):r().href=a}function E(b){if(!0!==B&&!(1!==b.which||b.metaKey||b.ctrlKey||b.shiftKey||b.defaultPrevented)){for(var d=b.target,c=r().href;d&&
"A"!==d.nodeName;)d=d.parentNode;!d||"A"!==d.nodeName||!d.hasAttribute("href")||d.hasAttribute("download")||"off"===d.getAttribute("data-routing")||d.target&&"_self"!==d.target||!(c=C===y(d)&&d.href!==c&&d.href.split("#")[0]!==c.split("#")[0])||(c=l(d,!1),!0===c&&(a.to({url:d.href,state:null}),b.preventDefault()))}}var r=b||z,D={},v={},u=null,C=y(r()),x=!1,B=!1;return{addRoute:function(a,b,d){if(!(a&&f(a.name)&&f(a.load)&&f(a.unload)))throw Error("First argument passed to Router.addRoute must be an application object.");
var c=a.name(),e=D[c],g=v[c];if(!c)throw Error("Application name must not be empty.");if(e&&e!==a)throw Error("An application named `"+c+"` already exists.");e||(D[c]=a);g||(v[c]=[]);a=new F(a,b,d);v[c].push(a);x&&(c=n(r(),u),!1!==c&&c.route===a&&q(c.route,c.params,r(),!1))},removeRoute:function(a){if(a&&a.application&&a.application().name){var b=a.application().name(),b=v[b];if(!b||!b.length)return!1;for(var d=0;d<b.length;d++)if(b[d]===a)return b.splice(d,1),!0;return!1}},route:g,to:function(b,
d){var c;b=A({url:r().href,state:{},history:!0},b);c=h.parse(b.url);!0===l(c,!0,!1,d)&&!1!==b.history&&a.to({url:b.url,state:b.state})},replace:function(b,d){var c;b=A({url:r().href,state:{},history:!0},b);c=h.parse(b.url);!0===l(c,!0,!0,d)&&!1!==b.history&&a.replace({url:b.url,state:b.state})},back:a.back,state:a.state,switchApp:function(a){a=D[a];u&&a&&(p(r(),a),l())},start:function(b){x||(x=!0,c.when("load").execute("routerBindStateChangeHandler",function(){x&&a.addStateChangeHandler(g)}),e.addEventListener("click",
E,!1),b=b?h.parse(b):m,l(b,!1))},stop:function(){x&&(a.removeStateChangeHandler(g),e.removeEventListener("click",E,!1),x=!1)},pause:function(){B=!0},unpause:function(){B=!1}}}var A=a.extend;a=a.mixin;var q={};a(q,t(new n));q.createRouter=t;q.ApplicationBase=C;return q});"use strict";c.register("rush-router-url-parser",function(){var a="protocol hostname host pathname port search hash href".split(" ");return{parse:function(d){var c=document.createElement("a"),e={};c.href=d;c.href=c.href;for(d=0;d<
a.length;d++)"pathname"===a[d]?e.pathname=c.pathname.replace(/(^\/?)/,"/"):e[a[d]]=c[a[d]];return e},toUrl:function(a){if(a)return a.protocol+"//"+a.host+a.pathname+a.search+a.hash}}})});