---
title: "Coursework"
author: "William Dennis"
date: "25/03/2021"
output: html_document
---

Question 3
Is the SSRI effective in treating anxiety and depression?

We built effective linear models using the step function

Looking at the summary of the the new models the P values of SSRI are both below 5% and reduce both phq and gad scores 


```{r test}
load('anxdep.rda')
df = na.omit(anxdep)
lmodgad = lm(gadfinal ~ gadinit + phqinit + treatment + sex + age + ethnic + finance + education + empstat + relstatus + depressedinpast, data = df)
lmodphq = lm(phqfinal ~ gadinit + phqinit + treatment + sex + age + ethnic + finance + education + empstat + relstatus + depressedinpast, data = df)
step(lmodgad)
step(lmodphq)
new_lmodgad = lm(gadfinal ~ treatment + depressedinpast + gadinit, data = df)
new_lmodphq = lm(phqfinal ~ relstatus + treatment + ethnic + empstat + finance + phqinit, data = df)
print(summary(new_lmodgad))
print(summary(new_lmodphq))
```

```{r }
load('anxdep.rda')
df = na.omit(anxdep)
dfSSRI = df[df$treatment == "SSRI",]
dfPLAC = df[df$treatment == "Placebo",]
new_lmodgadSSRI = lm(gadfinal ~ depressedinpast + gadinit, data = dfSSRI)
new_lmodgadPLAC = lm(gadfinal ~ depressedinpast + gadinit, data = dfPLAC)
summary(new_lmodgadSSRI)
summary(new_lmodgadPLAC)

new_lmodphqSSRI = lm(phqfinal ~ relstatus + ethnic + empstat + finance + phqinit, data = dfSSRI)
new_lmodphqPLAC = lm(phqfinal ~ relstatus + ethnic + empstat + finance + phqinit, data = dfPLAC)
summary(new_lmodphqSSRI)
summary(new_lmodphqPLAC)
```

Question 4

```{r data}
load('anxdep.rda')
df = na.omit(anxdep)
dfSSRI = df[df$treatment == "SSRI",]
dfPLAC = df[df$treatment == "Placebo",]

lmodgadSSRI = lm(gadfinal ~ gadinit + phqinit + sex + age + ethnic + finance + education + empstat + relstatus + depressedinpast, data = dfSSRI)
lmodphqSSRI = lm(phqfinal ~ gadinit + phqinit + sex + age + ethnic + finance + education + empstat + relstatus + depressedinpast, data = dfSSRI)
lmodgadPLAC = lm(gadfinal ~ gadinit + phqinit + sex + age + ethnic + finance + education + empstat + relstatus + depressedinpast, data = dfPLAC)
lmodphqPLAC = lm(phqfinal ~ gadinit + phqinit + sex + age + ethnic + finance + education + empstat + relstatus + depressedinpast, data = dfPLAC)

#step(lmodgadSSRI)
#step(lmodphqSSRI)
step(lmodgadPLAC)
step(lmodphqPLAC)

new_lmodgadSSRI = lm(gadfinal ~ depressedinpast + gadinit, data = dfSSRI)
new_lmodphqSSRI = lm(phqfinal ~ empstat + finance + phqinit, data = dfSSRI)
new_lmodgadPLAC = lm(gadfinal ~ depressedinpast + empstat + relstatus + education + finance + gadinit, data = dfPLAC)
new_lmodphqPLAC = lm(phqfinal ~ empstat + relstatus + finance + ethnic + phqinit, data = dfPLAC)

print(summary(new_lmodgadSSRI))
print(summary(new_lmodphqSSRI))
print(summary(new_lmodgadPLAC))
print(summary(new_lmodphqPLAC))

```

